### ISSUE TITLE
Error in starting app with custom obs-studio-node built with latest code

### ISSUE THREAD

**Issue by alokmahor** [Envek/obs-studio-node-example#39]
As dependency this app using 
```
"obs-studio-node": "https://obsstudionodes3.streamlabs.com/osn-0.10.10-release-win64.tar.gz"
```
I wanted to try custom built `obs-studio-node`. I created that using steps given in `README.md`
when I try to run app using custom `obs-studio-node` I am getting error

```
$ yarn start
yarn run v1.22.10
$ electron .

App threw an error during load
Error: The specified module could not be found.
\\?\C:\Users\User\projects\obs-studio-node-example\node_modules\obs-studio-node\obs_studio_client.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\User\projects\obs-studio-node-example\node_modules\obs-studio-node\module.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
```
I have confirmed that `C:\Users\User\projects\obs-studio-node-example\node_modules\obs-studio-node\obs_studio_client.node` exists.

My system details are:
OS: Windows 10 enterprise
Node: 14.16.0

**Comment by IbadAhmad80** [comment]
You would need to fetch the updated path for `obs-studio-node` from [here](https://github.com/stream-labs/desktop/blob/657e7fa6bd4b3f0072cad0c9b647a24fa7654f3b/package.json#L87)
